-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi

-- CONSTRAINTS

ALTER TABLE CARGO ADD CONSTRAINT FK_CARGO_DEPARTAMENTO
FOREIGN KEY (FK_IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_CARGO
FOREIGN KEY (FK_IDCARGO) REFERENCES CARGO(IDCARGO);

ALTER TABLE ENDERECO_FUNCIONARIO ADD CONSTRAINT FK_ENDERECO_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);

ALTER TABLE PONTO ADD CONSTRAINT FK_PONTO_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);

ALTER TABLE FERIAS ADD CONSTRAINT FK_FERIAS_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);

ALTER TABLE HISTORICO_FUNCIONAL ADD CONSTRAINT FK_HIST_FUNC_FUNCIONARIO
FOREIGN KEY (FK_IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO);

ALTER TABLE HISTORICO_FUNCIONAL ADD CONSTRAINT FK_HIST_FUNC_DEPARTAMENTO
FOREIGN KEY (FK_IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO);
