-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi

-- OBSERVAÇÃO: PROJETO FEITO EM LINUX, ENTÃO AS PASTAS CRIADAS NÃO ESTARÃO EM C:/

CREATE TABLESPACE RECURSOS_HUMANOS
	DATAFILE '/home/oracle/DATA/RH_01.DBF'
	SIZE 100M
	AUTOEXTEND ON
	NEXT 100M
	MAXSIZE 4096M;


/* PARA CHECAR AS TABLESPACES:
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;

OU

SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES
WHERE TABLESPACE_NAME = 'RECURSOS_HUMANOS';
*/


-- SEQUENCES
CREATE SEQUENCE SEQ_DEPARTAMENTO
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_CARGO
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_FUNCIONARIO
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_DEPENDENTE
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_PONTO
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_ENDERECO_FUNCIONARIO
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_FERIAS
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE SEQ_HISTORICO_FUNCIONAL
	START WITH 1
	INCREMENT BY 1;




-- TABELAS
CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT PRIMARY KEY,
	NOME_DEPARTAMENTO VARCHAR2(30) NOT NULL,
	LOCAL VARCHAR2(50) NOT NULL
)TABLESPACE RECURSOS_HUMANOS;


CREATE TABLE CARGO(
	IDCARGO INT PRIMARY KEY,
	NOME_CARGO VARCHAR2(30) NOT NULL,
	FAIXA_SALARIAL NUMBER(10,2) NOT NULL,
	FK_IDDEPARTAMENTO INT NOT NULL
)TABLESPACE RECURSOS_HUMANOS;


CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY,
	NOME_FUNCIONARIO VARCHAR2(50) NOT NULL UNIQUE,
	EMAIL_FUNCIONARIO VARCHAR2(50) NOT NULL UNIQUE,
	CPF VARCHAR2(14) NOT NULL UNIQUE,
	DATA_ADMISSAO DATE NOT NULL,
	SALARIO NUMBER(10,2) NOT NULL,
	FK_IDCARGO INT NOT NULL
)TABLESPACE RECURSOS_HUMANOS;


CREATE TABLE ENDERECO_FUNCIONARIO(
	IDENDERECO_FUNCIONARIO INT PRIMARY KEY,
	RUA VARCHAR2(30) NOT NULL,
	NUMERO VARCHAR2(10) NOT NULL,
	BAIRRO VARCHAR2(30) NOT NULL,
	CIDADE VARCHAR2(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CEP CHAR(9) NOT NULL,
	FK_IDFUNCIONARIO INT NOT NULL
)TABLESPACE RECURSOS_HUMANOS;


CREATE TABLE DEPENDENTE(
	IDDEPENDENTE INT PRIMARY KEY,
	NOME_DEPENDENTE VARCHAR2(50) NOT NULL,
	TIPO VARCHAR2(30) NOT NULL,
	FK_IDFUNCIONARIO INT NOT NULL
)TABLESPACE RECURSOS_HUMANOS;


CREATE TABLE PONTO(
	IDPONTO INT PRIMARY KEY,
	DATA_PONTO DATE DEFAULT SYSDATE,
	HORA_ENTRADA TIMESTAMP,
	HORA_SAIDA TIMESTAMP,
	FK_IDFUNCIONARIO INT NOT NULL
) TABLESPACE RECURSOS_HUMANOS;


CREATE TABLE FERIAS(
	IDFERIAS INT PRIMARY KEY,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NOT NULL,
	APROVADA CHAR(1) DEFAULT 'N' CHECK (APROVADA IN ('S', 'N')),
	FK_IDFUNCIONARIO INT NOT NULL
) TABLESPACE RECURSOS_HUMANOS;
-- Em "APROVADA" usar 'S' para SIM, 'N' para NÃO



CREATE TABLE HISTORICO_FUNCIONAL(
	IDHISTORICO_FUNCIONAL INT PRIMARY KEY,
	CARGO_ANTERIOR VARCHAR2(30) NOT NULL,
	CARGO_ATUAL VARCHAR2(30),
	DEPARTAMENTO_ANTERIOR VARCHAR2(30) NOT NULL,
	DEPARTAMENTO_ATUAL VARCHAR2(30),
	SALARIO_ANTERIOR NUMBER(10,2) NOT NULL,
	SALARIO_ATUAL NUMBER(10,2),
	FK_IDFUNCIONARIO INT NOT NULL,
	FK_IDDEPARTAMENTO INT NOT NULL
)TABLESPACE RECURSOS_HUMANOS;