-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi


-- TESTE DE PROCEDEURES
-- IMPORTANTE: ESTAMOS USANDO SELECT * SOMENTE POR SER AMBIENTE ACADEMICO COM POUCOS RESULTADOS.
-- ESTÁ SEM O FILTRO WHERE.


-- 1. BATER PONTO MANUALMENTE
EXEC PRC_BATER_PONTO(1, 'ENTRADA');
EXEC PRC_BATER_PONTO(1, 'SAIDA');
-- VERIFICAR EM: SELECT * FROM REGISTRO_PONTO;

-- 2. BONUS SALARIAL
EXEC PRC_BONUS(1, 10);
-- VERIFICAR EM: SELECT NOME_FUNCIONARIO, SALARIO FROM FUNCIONARIO;

-- 3. ATUALIZAÇÃO DE SALÁRIO
EXEC PRC_ATUALIZAR_SALARIO(1, 3000);
-- VERIFICAR EM: SELECT NOME_FUNCIONARIO, SALARIO FROM FUNCIONARIO;

-- 4. MÉDIA SALARIAL
EXEC PRC_MEDIA_SALARIAL_DEP(1);
-- JÁ APARECE O RESULTADO.

-- 5. CADASTRO VIA PROCEDURE
EXEC PRC_CADASTRO_FUNCIONARIO('ERICK VERONEZI', 'ERICKVERO@email.com', '12345678901', TO_DATE('2022-01-10','YYYY-MM-DD'), 2500, 1);
-- VERIFICAR EM: SELECT * FROM FUNCIONARIO;

-- 6. REGISTRAR FERIAS
EXEC PRC_MARCAR_FERIAS(1, TO_DATE('2024-12-20', 'YYYY-MM-DD'), TO_DATE('2025-01-05', 'YYYY-MM-DD'));
-- VERIFICAR EM: SELECT * FROM FERIAS;

-- 7. ATUALIZAR CARGO
EXEC PRC_ATUALIZAR_CARGO_FU(1, 4);
/* VERIFICAR EM:
		SELECT F.NOME_FUNCIONARIO, C.NOME_CARGO
		FROM FUNCIONARIO F
		JOIN CARGO C
		ON F.FK_IDCARGO = C.IDCARGO;
*/



-- PROJETAR VIEWS

-- 1. RELATÓRIO FUNCIONARIO
SELECT * FROM V_RELATORIO_FUNCIONARIO;

-- 2. RELATÓRIO ENDEREÇO
SELECT * FROM V_RELATORIO_ENDERECO;

-- 3. RELATÓRIO COMPLETO
SELECT * FROM V_RELATORIO_COMPLETO

-- 4. PONTO DE FUNCIONARIOS
SELECT * FROM V_PONTO_FUNCIONARIO

-- 5. FUNCIONARIOS COM FÉRIAS APROVADAS
SELECT * FROM V_FERIAS_APROVADAS

-- 6. LISTA COM FUNCIONÁRIOS COM DEPENDENTES
SELECT * FROM V_FUNCIONARIOS_DEPENDENTES

-- 7. LISTA COM HISTORICO DE FUNCIONARIOS
SELECT * FROM V_HISTORICO_FUNCIONARIO



-- TESTAR PACKAGE
EXEC PKG_FUNCIONARIO.CADASTRAR('ERICK SOUZA', 'ERIC@EMAIL.COM.BR', '98765432100', SYSDATE, 3500, 2);


EXEC PKG_FUNCIONARIO.ATUALIZAR_SALARIO(2, 3800);


EXEC PKG_FUNCIONARIO.LISTAR_FUNCIONARIOS;
