-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi

-- INSERTS


-- DEPARTAMENTO
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME_DEPARTAMENTO, LOCAL) VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Recursos Humanos', 'Prédio A - 2º Andar');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME_DEPARTAMENTO, LOCAL) VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Tecnologia da Informação', 'Prédio B - 3º Andar');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME_DEPARTAMENTO, LOCAL) VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Vendas', 'Prédio C');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME_DEPARTAMENTO, LOCAL) VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Marketing', 'Prédio C - 3º Andar');
INSERT INTO DEPARTAMENTO (IDDEPARTAMENTO, NOME_DEPARTAMENTO, LOCAL) VALUES (SEQ_DEPARTAMENTO.NEXTVAL, 'Financeiro', 'Prédio C - 4º Andar');

-- CARGO
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Analista de RH', 4500.00, 1);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Desenvolvedor', 6500.00, 2);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Contador', 5200.00, 5);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Coordenador de TI', 8000.00, 2);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Gerente de Vendas', 1200.00, 3);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Desenvolvedor', 6000.00, 2);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Desenvolvedor Junior', 2000.00, 2);
INSERT INTO CARGO (IDCARGO, NOME_CARGO, FAIXA_SALARIAL, FK_IDDEPARTAMENTO) VALUES (SEQ_CARGO.NEXTVAL, 'Especialista de Marketing', 6000.00, 4);


-- FUNCIONARIO
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Ana Costa', 'ana.costa@empresa.com', '12345678900', TO_DATE('2022-01-15','YYYY-MM-DD'), 4500.00, 1);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Bruno Lima', 'bruno.lima@empresa.com', '23456789011', TO_DATE('2021-03-20','YYYY-MM-DD'), 5200.00, 2);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Carla Nunes', 'carla.nunes@empresa.com', '34567890122', TO_DATE('2023-05-01','YYYY-MM-DD'), 3900.00, 3);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Daniel Rocha', 'daniel.rocha@empresa.com', '45678901233', TO_DATE('2020-07-11','YYYY-MM-DD'), 6000.00, 4);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Elisa Fernandes', 'elisa.fernandes@empresa.com', '56789012344', TO_DATE('2019-11-25','YYYY-MM-DD'), 7000.00, 5);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Felipe Martins', 'felipe.martins@empresa.com', '67890123455', TO_DATE('2022-06-10','YYYY-MM-DD'), 4800.00, 6);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Gabriela Souza', 'gabriela.souza@empresa.com', '78901234566', TO_DATE('2023-02-28','YYYY-MM-DD'), 4300.00, 7);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Henrique Almeida', 'henrique.almeida@empresa.com', '89012345677', TO_DATE('2021-09-17','YYYY-MM-DD'), 5300.00, 8);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Isabela Ribeiro', 'isabela.ribeiro@empresa.com', '90123456788', TO_DATE('2020-12-05','YYYY-MM-DD'), 4700.00, 1);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'João Mendes', 'joao.mendes@empresa.com', '01234567899', TO_DATE('2022-04-14','YYYY-MM-DD'), 6200.00, 2);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Karina Pires', 'karina.pires@empresa.com', '11122233344', TO_DATE('2018-10-01','YYYY-MM-DD'), 5600.00, 3);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Leonardo Cruz', 'leonardo.cruz@empresa.com', '22233344455', TO_DATE('2023-08-07','YYYY-MM-DD'), 3900.00, 4);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Mariana Torres', 'mariana.torres@empresa.com', '33344455566', TO_DATE('2021-01-12','YYYY-MM-DD'), 4100.00, 5);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Nathan Oliveira', 'nathan.oliveira@empresa.com', '44455566677', TO_DATE('2019-04-22','YYYY-MM-DD'), 5800.00, 6);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Olívia Azevedo', 'olivia.azevedo@empresa.com', '55566677788', TO_DATE('2022-11-11','YYYY-MM-DD'), 4500.00, 7);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Pedro Henrique', 'pedro.henrique@empresa.com', '66677788899', TO_DATE('2020-02-09','YYYY-MM-DD'), 5000.00, 8);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Queila Barbosa', 'queila.barbosa@empresa.com', '77788899900', TO_DATE('2023-03-27','YYYY-MM-DD'), 4700.00, 1);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Rodrigo Assis', 'rodrigo.assis@empresa.com', '88899900011', TO_DATE('2021-06-18','YYYY-MM-DD'), 6400.00, 2);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Sabrina Castro', 'sabrina.castro@empresa.com', '99900011122', TO_DATE('2019-09-05','YYYY-MM-DD'), 5200.00, 3);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Tiago Gonçalves', 'tiago.goncalves@empresa.com', '00011122233', TO_DATE('2022-07-21','YYYY-MM-DD'), 5900.00, 4);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Ana Souza', 'ana.souza@empresa.com', '123.456.789-00', TO_DATE('2022-03-15','YYYY-MM-DD'), 4600.00, 5);
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Carlos Lima', 'carlos.lima@empresa.com', '987.654.321-00', TO_DATE('2021-08-01','YYYY-MM-DD'), 6700.00, 6);


-- ENDERECO_FUNCIONARIO
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DAS FLORES', '123', 'CENTRO', 'SÃO PAULO', 'SP', '01000-000', 1);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'AV. BRASIL', '456', 'JARDINS', 'SÃO PAULO', 'SP', '01400-000', 2);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA VERDE', '789', 'VILA MARIANA', 'SÃO PAULO', 'SP', '04100-000', 3);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DO SOL', '101', 'PARQUE SOLAR', 'CAMPINAS', 'SP', '13010-000', 4);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'AV. DAS PALMEIRAS', '202', 'JARDIM PALMEIRAS', 'RIBEIRÃO PRETO', 'SP', '14020-000', 5);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DAS ACÁCIAS', '303', 'VILA ACÁCIA', 'SANTOS', 'SP', '11010-000', 6);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DO CAFÉ', '404', 'BAIRRO CAFÉ', 'FRANCA', 'SP', '14400-000', 7);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'AV. LIBERDADE', '505', 'LIBERDADE', 'SÃO PAULO', 'SP', '01500-000', 8);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DAS LARANJEIRAS', '606', 'VILA FRUTA', 'INDAIATUBA', 'SP', '13330-000', 9);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DO RIBEIRÃO', '707', 'JARDIM DO RIBEIRÃO', 'RIBEIRÃO PRETO', 'SP', '14015-000', 10);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DO CEDRO', '808', 'BAIRRO DAS ÁRVORES', 'SANTOS', 'SP', '11013-000', 11);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA TOKYO', '81', 'BAIRRO CEREJEIRAS', 'ATIBAIA', 'SP', '11053-000', 12);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'AV. DOS ESTUDANTES', '111', 'UNIVERSITÁRIO', 'TAUBATÉ', 'SP', '12020-000', 13);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DAS AQUARELAS', '222', 'VILA DAS ARTES', 'SÃO PAULO', 'SP', '03122-000', 14);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA FLOR VERDE', '213', 'VILA DAS FLORES', 'SÃO PAULO', 'SP', '04172-000', 15);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'AV. MARGINAL', '444', 'CENTRO', 'FRANCA', 'SP', '14401-000', 16);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DOS PINHEIROS', '555', 'PINHEIRINHO', 'COTIA', 'SP', '06722-000', 17);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA DO ENGENHO', '666', 'ENGENHO VELHO', 'ATIBAIA', 'SP', '12942-121', 18);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA TIETÊ', '777', 'VILA TIETÊ', 'SÃO PAULO', 'SP', '03110-000', 19);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA ALVORADA', '888', 'ALVORADA', 'SANTO ANDRÉ', 'SP', '09020-000', 20);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA B', '361', 'SANTA MARIA', 'CAMPINAS', 'SP', '47641-857', 21);
INSERT INTO ENDERECO_FUNCIONARIO (IDENDERECO_FUNCIONARIO, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, FK_IDFUNCIONARIO) VALUES (SEQ_ENDERECO_FUNCIONARIO.NEXTVAL, 'RUA ALAGOAS', '706', 'JARDIM', 'CAMPINAS', 'SP', '63476-892', 22);

-- PONTO
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 1);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 2);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('07:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 3);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 4);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 5);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('10:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 6);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 7);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 8);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 9);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 10);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 11);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 12);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('07:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 13);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('07:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 14);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('07:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 15);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 16);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 17);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 18);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 19);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:30:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 20);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('08:45:00', 'HH24:MI:SS'), TO_TIMESTAMP('17:00:00', 'HH24:MI:SS'), 21);
INSERT INTO PONTO (IDPONTO, DATA_PONTO, HORA_ENTRADA, HORA_SAIDA, FK_IDFUNCIONARIO) VALUES (SEQ_PONTO.NEXTVAL, SYSDATE, TO_TIMESTAMP('09:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('18:00:00', 'HH24:MI:SS'), 22);

-- DEPENDENTE
INSERT INTO DEPENDENTE (IDDEPENDENTE, NOME_DEPENDENTE, TIPO, FK_IDFUNCIONARIO)VALUES (SEQ_DEPENDENTE.NEXTVAL, 'Lucas Souza', 'Filho', 11);
INSERT INTO DEPENDENTE (IDDEPENDENTE, NOME_DEPENDENTE, TIPO, FK_IDFUNCIONARIO)VALUES (SEQ_DEPENDENTE.NEXTVAL, 'Mariana Lima', 'Cônjuge', 5);
INSERT INTO DEPENDENTE (IDDEPENDENTE, NOME_DEPENDENTE, TIPO, FK_IDFUNCIONARIO)VALUES (SEQ_DEPENDENTE.NEXTVAL, 'Pedro Alves', 'Filho', 8);
INSERT INTO DEPENDENTE (IDDEPENDENTE, NOME_DEPENDENTE, TIPO, FK_IDFUNCIONARIO)VALUES (SEQ_DEPENDENTE.NEXTVAL, 'Carlos Silva', 'Cônjuge', 13);
INSERT INTO DEPENDENTE (IDDEPENDENTE, NOME_DEPENDENTE, TIPO, FK_IDFUNCIONARIO)VALUES (SEQ_DEPENDENTE.NEXTVAL, 'João Ferreira', 'Filho', 20);
INSERT INTO DEPENDENTE (IDDEPENDENTE, NOME_DEPENDENTE, TIPO, FK_IDFUNCIONARIO)VALUES (SEQ_DEPENDENTE.NEXTVAL, 'Pedro Luciano', 'Pai', 2);


-- FERIAS
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-03-10','YYYY-MM-DD'), TO_DATE('2024-04-25','YYYY-MM-DD'), 'S', 2);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-07-11','YYYY-MM-DD'), TO_DATE('2024-08-15','YYYY-MM-DD'), 'N', 3);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-08-31','YYYY-MM-DD'), TO_DATE('2023-09-30','YYYY-MM-DD'), 'N', 4);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-12-17','YYYY-MM-DD'), TO_DATE('2024-01-17','YYYY-MM-DD'), 'S', 6);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-01-10','YYYY-MM-DD'), TO_DATE('2024-02-25','YYYY-MM-DD'), 'S', 7);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-11-01','YYYY-MM-DD'), TO_DATE('2024-12-15','YYYY-MM-DD'), 'N', 8);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-10-31','YYYY-MM-DD'), TO_DATE('2023-11-30','YYYY-MM-DD'), 'N', 9);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-02-27','YYYY-MM-DD'), TO_DATE('2023-03-17','YYYY-MM-DD'), 'S', 10);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-01-20','YYYY-MM-DD'), TO_DATE('2024-02-25','YYYY-MM-DD'), 'S', 11);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-03-11','YYYY-MM-DD'), TO_DATE('2024-04-15','YYYY-MM-DD'), 'N', 12);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-02-21','YYYY-MM-DD'), TO_DATE('2023-03-30','YYYY-MM-DD'), 'N', 13);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-03-27','YYYY-MM-DD'), TO_DATE('2023-04-17','YYYY-MM-DD'), 'S', 14);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-04-10','YYYY-MM-DD'), TO_DATE('2024-05-25','YYYY-MM-DD'), 'S', 15);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-07-04','YYYY-MM-DD'), TO_DATE('2024-08-15','YYYY-MM-DD'), 'N', 16);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-05-23','YYYY-MM-DD'), TO_DATE('2023-06-30','YYYY-MM-DD'), 'N', 17);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-03-16','YYYY-MM-DD'), TO_DATE('2023-04-17','YYYY-MM-DD'), 'S', 18);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-04-11','YYYY-MM-DD'), TO_DATE('2024-05-25','YYYY-MM-DD'), 'S', 19);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2024-07-14','YYYY-MM-DD'), TO_DATE('2024-08-15','YYYY-MM-DD'), 'N', 20);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-01-30','YYYY-MM-DD'), TO_DATE('2024-03-02','YYYY-MM-DD'), 'N', 21);
INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES (SEQ_FERIAS.NEXTVAL, TO_DATE('2023-07-01','YYYY-MM-DD'), TO_DATE('2023-08-17','YYYY-MM-DD'), 'S', 22);


-- HISTORICO_FUNCIONAL
INSERT INTO HISTORICO_FUNCIONAL (IDHISTORICO_FUNCIONAL, CARGO_ANTERIOR, CARGO_ATUAL, DEPARTAMENTO_ANTERIOR, DEPARTAMENTO_ATUAL,SALARIO_ANTERIOR, SALARIO_ATUAL, FK_IDFUNCIONARIO, FK_IDDEPARTAMENTO)
VALUES (SEQ_HISTORICO_FUNCIONAL.NEXTVAL,'Estagiário', 'Analista de RH', 'Recursos Humanos', 'Recursos Humanos', 1500.00, 4600.00,1, 1);

INSERT INTO HISTORICO_FUNCIONAL (IDHISTORICO_FUNCIONAL, CARGO_ANTERIOR, CARGO_ATUAL, DEPARTAMENTO_ANTERIOR, DEPARTAMENTO_ATUAL,SALARIO_ANTERIOR, SALARIO_ATUAL, FK_IDFUNCIONARIO, FK_IDDEPARTAMENTO)
VALUES (SEQ_HISTORICO_FUNCIONAL.NEXTVAL,'Assistente', 'Contador', 'Financeiro', 'Financeiro', 3000.00, 5200.00, 3, 5);

INSERT INTO HISTORICO_FUNCIONAL (IDHISTORICO_FUNCIONAL, CARGO_ANTERIOR, CARGO_ATUAL, DEPARTAMENTO_ANTERIOR, DEPARTAMENTO_ATUAL,SALARIO_ANTERIOR, SALARIO_ATUAL, FK_IDFUNCIONARIO, FK_IDDEPARTAMENTO) 
VALUES (SEQ_HISTORICO_FUNCIONAL.NEXTVAL, 'Estagiário', 'Analista de RH', 'Departamento Pessoal', 'Recursos Humanos', 1800.00, 4000.00, 1, 1);
