-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi

CREATE OR REPLACE PACKAGE PKG_FUNCIONARIO AS
  PROCEDURE CADASTRAR (P_NOME VARCHAR2,
                      P_EMAIL VARCHAR2,
                      P_CPF VARCHAR2,
                      P_DATA_ADMISSAO DATE,
                      P_SALARIO NUMBER,
                      P_IDCARGO NUMBER);

  PROCEDURE ATUALIZAR_SALARIO (P_IDFUNCIONARIO NUMBER,
                              P_NOVO_SALARIO NUMBER);

  PROCEDURE LISTAR_FUNCIONARIOS;
END PKG_FUNCIONARIO;
/

CREATE OR REPLACE PACKAGE BODY PKG_FUNCIONARIO AS

  PROCEDURE CADASTRAR(P_NOME VARCHAR2,
                      P_EMAIL VARCHAR2,
                      P_CPF VARCHAR2,
                      P_DATA_ADMISSAO DATE,
                      P_SALARIO NUMBER,
                      P_IDCARGO NUMBER) IS
  BEGIN
    INSERT INTO FUNCIONARIO(IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO)
    VALUES(SEQ_FUNCIONARIO.NEXTVAL, P_NOME, P_EMAIL, P_CPF, P_DATA_ADMISSAO, P_SALARIO, P_IDCARGO);
    COMMIT;
  END;

  PROCEDURE ATUALIZAR_SALARIO(P_IDFUNCIONARIO IN NUMBER, P_NOVO_SALARIO IN NUMBER) IS
  BEGIN
    UPDATE FUNCIONARIO SET SALARIO = P_NOVO_SALARIO
    WHERE IDFUNCIONARIO = P_IDFUNCIONARIO;
    COMMIT;
  END;

  PROCEDURE LISTAR_FUNCIONARIOS IS
  BEGIN
    FOR r IN (SELECT * FROM FUNCIONARIO) LOOP
      DBMS_OUTPUT.PUT_LINE(r.NOME_FUNCIONARIO || ' - ' || r.SALARIO);
    END LOOP;
  END;

END PKG_FUNCIONARIO;
/
