-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi

-- 1. PROCEDURE PRA BATER PONTO MANUALMENTE
CREATE OR REPLACE PROCEDURE PRC_BATER_PONTO(P_IDFUNCIONARIO REGISTRO_PONTO.IDFUNCIONARIO%TYPE, P_TIPO_EVENTO REGISTRO_PONTO.TIPO_EVENTO%TYPE) IS
BEGIN
  INSERT INTO REGISTRO_PONTO (ID_PONTO, IDFUNCIONARIO, TIPO_EVENTO)
  VALUES (SEQ_REGISTRO_PONTO.NEXTVAL, P_IDFUNCIONARIO, UPPER(P_TIPO_EVENTO));
END;
/


-- 2. BONUS SALARIAL
CREATE OR REPLACE PROCEDURE PRC_BONUS(P_IDFUNCIONARIO FUNCIONARIO.IDFUNCIONARIO%TYPE, P_PERCENT NUMBER)
AS
  BEGIN

      UPDATE FUNCIONARIO SET SALARIO = SALARIO + (SALARIO *(P_PERCENT /100))
      WHERE IDFUNCIONARIO = P_IDFUNCIONARIO;
  END;
  /


-- 3. ATUALIZAR UM SALARIO
CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_SALARIO (P_IDFUNCIONARIO FUNCIONARIO.IDFUNCIONARIO%TYPE, P_NOVO_SALARIO FUNCIONARIO.SALARIO%TYPE)
AS
BEGIN
  UPDATE FUNCIONARIO
  SET SALARIO = P_NOVO_SALARIO
  WHERE IDFUNCIONARIO = P_IDFUNCIONARIO;

  COMMIT;
END;
/

-- 4. CALCULAR MEDIA SALARIAL DE DEPARTAMENTOS
CREATE OR REPLACE PROCEDURE PRC_MEDIA_SALARIAL_DEP (P_IDDEPARTAMENTO DEPARTAMENTO.IDDEPARTAMENTO%TYPE)
AS
  V_MEDIA NUMBER;
BEGIN
  SELECT ROUND(AVG(F.SALARIO), 2)
  INTO V_MEDIA
  FROM FUNCIONARIO F
  JOIN CARGO C ON F.FK_IDCARGO = C.IDCARGO
  WHERE C.FK_IDDEPARTAMENTO = P_IDDEPARTAMENTO;

  DBMS_OUTPUT.PUT_LINE('Média salarial do departamento: ' || V_MEDIA);
END;
/



-- 5. CADASTRO DE FUNCIONARIOS POR PROCEDURE
CREATE OR REPLACE PROCEDURE PRC_CADASTRO_FUNCIONARIO  (P_NOME FUNCIONARIO.NOME_FUNCIONARIO%TYPE,
                                                      P_EMAIL FUNCIONARIO.EMAIL_FUNCIONARIO%TYPE,
                                                      P_CPF FUNCIONARIO.CPF%TYPE,
                                                      P_DATA_ADMISSAO FUNCIONARIO.DATA_ADMISSAO%TYPE,
                                                      P_SALARIO FUNCIONARIO.SALARIO%TYPE,
                                                      P_IDCARGO FUNCIONARIO.FK_IDCARGO%TYPE)
AS
  BEGIN

      INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, CPF, DATA_ADMISSAO, SALARIO, FK_IDCARGO) VALUES
      (SEQ_FUNCIONARIO.NEXTVAL, P_NOME, P_EMAIL, P_CPF, P_DATA_ADMISSAO, P_SALARIO, P_IDCARGO);

      COMMIT;
  END;
  /


-- 6. REGISTRAR FÉRIAS APROVADAS 
  CREATE OR REPLACE PROCEDURE PRC_MARCAR_FERIAS (P_IDFUNCIONARIO FUNCIONARIO.IDFUNCIONARIO%TYPE,
                                                P_DATA_INICIO DATE,
                                                P_DATA_FIM DATE)
AS
BEGIN

  INSERT INTO FERIAS (IDFERIAS, DATA_INICIO, DATA_FIM, APROVADA, FK_IDFUNCIONARIO) VALUES 
  (SEQ_FERIAS.NEXTVAL, P_DATA_INICIO, P_DATA_FIM, 'S', P_IDFUNCIONARIO);

  COMMIT;
END;
/

-- 7. ATUALIZAR UM CARGO DE FUNCIONARIO
CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_CARGO_FU (P_IDFUNCIONARIO FUNCIONARIO.IDFUNCIONARIO%TYPE,
                                                            P_NOVO_CARGO FUNCIONARIO.FK_IDCARGO%TYPE)
AS
BEGIN
      UPDATE FUNCIONARIO
      SET FK_IDCARGO = P_NOVO_CARGO
      WHERE IDFUNCIONARIO = P_IDFUNCIONARIO;

      COMMIT;
END;
/