-- PROJETO ORACLE - SISTEMA RH
-- https://github.com/ErickVeronezi


CREATE OR REPLACE VIEW V_RELATORIO_FUNCIONARIO AS
SELECT 	F.NOME_FUNCIONARIO,
		F.EMAIL_FUNCIONARIO,
		F.CPF, F.DATA_ADMISSAO,
		F.SALARIO,
		C.NOME_CARGO,
		C.FAIXA_SALARIAL,
		D.NOME_DEPARTAMENTO,
		D.LOCAL
FROM FUNCIONARIO F
JOIN CARGO C
ON F.FK_IDCARGO = C.IDCARGO
JOIN DEPARTAMENTO D
ON C.FK_IDDEPARTAMENTO = D.IDDEPARTAMENTO
ORDER BY NOME_FUNCIONARIO;



CREATE OR REPLACE VIEW V_RELATORIO_ENDERECO AS
SELECT 	F.NOME_FUNCIONARIO,
		F.CPF,
		E.RUA,
		E.NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO,
		E.CEP
FROM FUNCIONARIO F
INNER JOIN ENDERECO_FUNCIONARIO E
ON E.FK_IDFUNCIONARIO = F.IDFUNCIONARIO
ORDER BY NOME_FUNCIONARIO;



CREATE OR REPLACE VIEW V_RELATORIO_COMPLETO AS
SELECT 	F.NOME_FUNCIONARIO,
		F.EMAIL_FUNCIONARIO,
		F.CPF, F.DATA_ADMISSAO,
		F.SALARIO,
		C.NOME_CARGO,
		C.FAIXA_SALARIAL,
		D.NOME_DEPARTAMENTO,
		D.LOCAL,
		E.RUA,
		E.NUMERO,
		E.BAIRRO,
		E.CIDADE,
		E.ESTADO,
		E.CEP
FROM FUNCIONARIO F
JOIN CARGO C
ON F.FK_IDCARGO = C.IDCARGO
JOIN DEPARTAMENTO D
ON C.FK_IDDEPARTAMENTO = D.IDDEPARTAMENTO
INNER JOIN ENDERECO_FUNCIONARIO E
ON E.FK_IDFUNCIONARIO = F.IDFUNCIONARIO
ORDER BY NOME_FUNCIONARIO;



CREATE OR REPLACE VIEW V_PONTO_FUNCIONARIO AS
SELECT 	F.NOME_FUNCIONARIO,
		F.EMAIL_FUNCIONARIO,
		C.NOME_CARGO,
		P.DATA_PONTO,
		P.HORA_ENTRADA,
		P.HORA_SAIDA 
FROM FUNCIONARIO F
JOIN CARGO C
ON F.FK_IDCARGO = C.IDCARGO
JOIN PONTO P
ON P.FK_IDFUNCIONARIO = F.IDFUNCIONARIO;



CREATE OR REPLACE VIEW V_FERIAS_APROVADAS AS
SELECT 	F.NOME_FUNCIONARIO,
		FE.DATA_INICIO,
		FE.DATA_FIM
FROM FUNCIONARIO F
JOIN FERIAS FE ON FE.FK_IDFUNCIONARIO = F.IDFUNCIONARIO
WHERE FE.APROVADA = 'S';



CREATE OR REPLACE VIEW V_FUNCIONARIOS_DEPENDENTES AS
SELECT 	F.NOME_FUNCIONARIO,
		D.NOME_DEPENDENTE,
		D.TIPO
FROM FUNCIONARIO F
JOIN DEPENDENTE D ON D.FK_IDFUNCIONARIO = F.IDFUNCIONARIO
ORDER BY NOME_FUNCIONARIO;



CREATE OR REPLACE VIEW V_HISTORICO_FUNCIONARIO AS
SELECT 	F.NOME_FUNCIONARIO,
		H.CARGO_ANTERIOR,
		H.CARGO_ATUAL, 
		H.SALARIO_ANTERIOR,
		H.SALARIO_ATUAL,
       	H.DEPARTAMENTO_ANTERIOR,
       	H.DEPARTAMENTO_ATUAL
FROM FUNCIONARIO F
JOIN HISTORICO_FUNCIONAL H ON H.FK_IDFUNCIONARIO = F.IDFUNCIONARIO;
